name: pos_kawani
description: "POS System of Kedai Kawani"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.6
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  http: ^1.2.1
  flutter_dotenv: ^5.1.0
  cached_network_image: ^3.3.1
  flutter_rating_bar: ^4.0.1
  mocktail: ^1.0.3
  intl: ^0.19.0
  flexible_grid_view: ^0.0.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  very_good_analysis: ^5.1.0
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/config/
    - assets/config/.env
    - assets/images/
    - assets/images/example_image.jpg
    - assets/images/logo.png
